### ISSUE TITLE
Error parsing 'Gemfile': no such file to load -- xlsx_streaming_reader

### ISSUE THREAD

**Issue by Synkronicity** [hudmol/as_spreadsheet_bulk_updater#4]
Hi,

I have the digitization_work_order plugin successfully installed but I can't seem to get as_spreadsheet_bulk_updater to initialize with the ArchivesSpace initialize-plugin.sh script. The plugin is renamed to remove the version number. When I initialize it I get the following error:

```
[!] There was an error parsing `Gemfile`: no such file to load -- xlsx_streaming_reader. Bundler cannot continue.

 #  from /opt/archivesspace_2_8_1/plugins/as_spreadsheet_bulk_updater/Gemfile:43
 #  -------------------------------------------
 #  local_gems.each do |gem|
 >    require gem.fetch(:gem)
 #  end
 #  -------------------------------------------
```

I can resolve this by manually downloading and plopping the xlsx_streaming_reader gem into the local_gems directory (sans version number). initialize-plugin.sh then succeeds with the following:

`Successfully installed bundler-2.1.4`
`Parsing documentation for bundler-2.1.4`
`Done installing documentation for bundler after 6 seconds`
`1 gem installed`
`Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.`
`The Gemfile specifies no dependencies`
`Resolving dependencies...`
`Bundle complete! 0 Gemfile dependencies, 1 gem now installed.`
`Use `bundle info [gemname]` to see where a bundled gem is installed.`

But when I try to run ASpace I get a looping initialization error:

```
INFO: INFO: resetting rack response due exception: org.jruby.rack.RackInitializationException:
[!] There was an error parsing `Gemfile`: no such file to load -- xlsx_streaming_reader. Bundler cannot continue.

 #  from /opt/archivesspace_2_8_1/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/Gemfile:64
 #  -------------------------------------------
 #  require 'asutils'
 >  ASUtils.load_plugin_gems(self)
 #  -------------------------------------------

        from org/jruby/RubyKernel.java:974:in `require'
        from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from (eval):43:in `block in (eval)'
        from org/jruby/RubyArray.java:1809:in `each'
        from (eval):42:in `(eval)'
        from org/jruby/RubyBasicObject.java:2628:in `instance_eval'
        from uri:classloader:/asutils.rb:253:in `block in load_plugin_gems'
        from org/jruby/RubyArray.java:1809:in `each'
        from uri:classloader:/asutils.rb:249:in `load_plugin_gems'
        from /opt/archivesspace_2_8_1/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/Gemfile:64:in `(eval)'
        from org/jruby/RubyBasicObject.java:2640:in `instance_eval'
        from /opt/archivesspace_2_8_1/gems/gems/bundler-2.1.4/lib/bundler/dsl.rb:47:in `eval_gemfile'
        from /opt/archivesspace_2_8_1/gems/gems/bundler-2.1.4/lib/bundler/dsl.rb:12:in `evaluate'
        from /opt/archivesspace_2_8_1/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:34:in `build'
        from /opt/archivesspace_2_8_1/gems/gems/bundler-2.1.4/lib/bundler.rb:195:in `definition'
        from /opt/archivesspace_2_8_1/gems/gems/bundler-2.1.4/lib/bundler.rb:143:in `setup'
        from /opt/archivesspace_2_8_1/gems/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <main>'
        from /opt/archivesspace_2_8_1/gems/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
        from /opt/archivesspace_2_8_1/gems/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
        from /opt/archivesspace_2_8_1/gems/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<main>'
        from org/jruby/RubyKernel.java:974:in `require'
        from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:130:in `require'
        from /opt/archivesspace_2_8_1/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/app/main.rb:1:in `<main>'
        from org/jruby/RubyKernel.java:974:in `require'
        from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/archivesspace_2_8_1/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/config.ru:4:in `block in <main>'
        from org/jruby/RubyBasicObject.java:2622:in `instance_eval'
        from uri:classloader:/vendor/rack-2.2.3/rack/builder.rb:125:in `initialize'
        from /opt/archivesspace_2_8_1/data/tmp/jetty-0.0.0.0-8089-backend.war-_-any-/webapp/WEB-INF/config.ru:1:in `<main>'
        from launcher/launcher.rb:92:in `start_server'
        from launcher/launcher.rb:157:in `main'
        from launcher/launcher.rb:261:in `<main>'

```
Any ideas about how I should proceed? Let me know if you need any more details.

Thanks,
Will Bonnett
George Washington University Libraries

**Comment by payten** [comment]
Hi @Synkronicity,

We've just released a new version that should fix your issue:

> https://github.com/hudmol/as_spreadsheet_bulk_updater/releases/tag/v1.1

Version 1.0 had a non-documented prerequisite that the server have `git` installed.  We've changed things to drop that requirement.

Thanks!
